QRiMovWeb/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace QRiMovWeb.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

QRiMovWeb/Controllers/FavoritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QRiMovWeb.Models;
using QRiMovWeb.Repoositories;
using QRiMovWeb.ViewModels;

namespace QRiMovWeb.Controllers
{
    public class FavoritoController : Controller
    {
        private readonly IImovelRepository _imovelRepository;
        private readonly Favorito _favorito;

        public FavoritoController(IImovelRepository imovelRepository,Favorito favorito)
        {
            _imovelRepository = imovelRepository;
            _favorito = favorito;
        }

        public IActionResult Index()
        {
            var itens = _favorito.GetFavoritoItems();
            _favorito.FavoritoItems = itens;

            var favoritoViewModel = new FavoritoViewModel
            {
                Favorito = _favorito,
                FavoritoTotal = _favorito.GetFavoritoTotal()
            };
            return View(favoritoViewModel);
        }
        public IActionResult Details()
        {
            var itens = _favorito.GetFavoritoItems();
            _favorito.FavoritoItems = itens;

            var favoritoViewModel = new FavoritoViewModel
            {
                Favorito = _favorito,
                FavoritoTotal = _favorito.GetFavoritoTotal()
            };
            return View(favoritoViewModel);
        }
        [Authorize]
        public RedirectToActionResult AdicionarItemNosFavoritos(int imovelId)
        {
            var imovelSelecionado = _imovelRepository.Imoveis.FirstOrDefault(p => p.ImovelId == imovelId);
            if (imovelSelecionado != null)
                _favorito.AdicionarFavorito(imovelSelecionado, 1);
            return RedirectToAction("Index");
        }
        [Authorize]
        public IActionResult RemoverItemDosFavoritos(int imovelId)
        {
            var imovelSelecionado = _imovelRepository.Imoveis.FirstOrDefault(p => p.ImovelId == imovelId);
            if (imovelSelecionado != null)
                _favorito.RemoverFavorito(imovelSelecionado);
            return RedirectToAction("Index");
        }
    }
}

QRiMovWeb/Controllers/ImovelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using QRiMovWeb.Models;
using QRiMovWeb.Repoositories;
using QRiMovWeb.ViewModels;

namespace QRiMovWeb.Controllers
{
    public class ImovelController : Controller
    {
        private readonly IImovelRepository _imovelRepository;
        private readonly ICategoriaRepository _categoriaRepository;

        public ImovelController(IImovelRepository imovelRepository,ICategoriaRepository categoriaRepository)
        {
            _imovelRepository = imovelRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult List(string categoria)
        {
            string _categoria = categoria;
            IEnumerable<Imovel> imoveis;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                imoveis = _imovelRepository.Imoveis.OrderBy(i => i.ImovelId);
                categoria = "Todos os Imóveis";
            }
            else
            {
                if (string.Equals("Venda", _categoria, StringComparison.OrdinalIgnoreCase))
                {
                    imoveis = _imovelRepository.Imoveis.Where(i => i.Categoria.CategoriaNome.Equals("Venda")).OrderBy(i => i.Descricao);
                }
                else
                {
                    imoveis = _imovelRepository.Imoveis.Where(i => i.Categoria.CategoriaNome.Equals("Aluguel")).OrderBy(i => i.Descricao);
                }
                categoriaAtual = _categoria;
            }
            var imoveisListViewModel = new ImovelListViewModel
            {
                Imoveis = imoveis,
                CategoriaAtual = categoriaAtual
            };
            
            return View(imoveisListViewModel);
        }
        public IActionResult Details(int imovelId)
        {
            var imovel = _imovelRepository.Imoveis.FirstOrDefault(i => i.ImovelId == imovelId);
            /*if (imovel == null)
            {
                return View("../Views/Error/Error.cshtml");
            }*/
            return View(imovel);
        }
        public IActionResult search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Imovel> imoveis;
            string _categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                imoveis = _imovelRepository.Imoveis.OrderBy(i => i.ImovelId);
            }
            else
            {
                imoveis = _imovelRepository.Imoveis.Where(i => i.Descricao.ToLower().Contains(_searchString.ToLower()));
            }
            return View("~/Views/Imovel/List.cshtml", new ImovelListViewModel { Imoveis = imoveis, CategoriaAtual = "Todos os imóveis" });
        }
    }
}

QRiMovWeb/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/images/carousel111.jpg" alt="" width="1000" height="400" style="margin-left: auto;margin-right:auto;">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/carousel222.jpg" alt="" width="1000" height="400" style="margin-left: auto;margin-right:auto;">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/carousel333.jpg" alt="" width="1000" height="400"style="margin-left: auto;margin-right:auto;">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/images/carousel444.jpg" alt="" width="1000" height="400" style="margin-left: auto;margin-right:auto;">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

QRiMovWeb/Views/Shared/_ImoveisResumo.cshtml
@model Imovel
<div class="col-sm-4 col-lg-4 col-md-4 ">
    <div class="thumbnail" style="height:400px;overflow:hidden;" >
        <img src="@Model.ImgUrl" class="img-rounded" alt="@Model.Descricao" style="height:145px;width:225px;overflow:hidden;" width="225" height="225" />
        <div class="caption">
            <h3 class="pull-right badge badge-pill badge-primary">@Model.Categoria.CategoriaNome</h3>
            <h3>
                <a asp-controller="Imovel" asp-action="Details" asp-route-ImovelId="@Model.ImovelId">@Model.Descricao</a>
            </h3> 
            <h3>@Model.Valor.ToString("c")</h3>
            <h4>@Model.UF, @Model.Comarca</h4>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-warning" id="cartButton" asp-controller="Favorito" asp-action="AdicionarItemNosFavoritos" asp-route-imovelId="@Model.ImovelId">
                    <span class="glyphicon glyphicon-star"></span> Favoritar
                </a>
            </p>
        </div>
    </div>
</div>

QRiMovWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - QRiMovWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">  <img src="~/images/qrimov11.png" alt="Fale conosco" style="width:20px;height:20px;" /></a>
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoriaMenu")
                    <li><a asp-area="" asp-controller="Contato" asp-action="Index">Contato</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        @await Component.InvokeAsync("FavoritoResumo")
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial")

                <form class="navbar-form navbar-right" asp-controller="Imovel" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Procurar imóvel" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content text-center">
        @RenderBody()
        <hr />
        <footer class="navbar-fixed-bottom">
            <p>&copy; Todos direitos reservados 2020 - QRiMov</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>